### ISSUE TITLE
RELRO Binaries Does Not Check Memory Permissions

### ISSUE THREAD

**Issue by arcsign** [kubo/plthook#1]
Hi,

First of all this code is very well written, nice job. When dealing with RELRO binaries plthook tries to write to memory that is read only. My proposed solution to this is to check if the binary is RELRO and then change the memory permissions so it is writable and then change the permissions after hooking. You could just always call mprotect and make it RW and then make it readonly afterwards, however, you want to know if it is RELRO or not so that you can keep the memory permissions the same after hooking. 

I can work on implementing this sometime later, but I thought I would open an issue about it now. My solution right now has just been to call mprotect and make the memory readable and writable, but this doesn't change the memory permissions back to what they were originally before hooking...

**Comment by kubo** [comment]
@arcsign 
Thank you! I had overlooked this issue until today.
I fixed it. See 6c6d0d3667d9f3583ef811efc44d6bbe482f34ad.
It checks whether the target address is in the RELRO region or not and changes the process memory protection if it is needed.
