### ISSUE TITLE
I try to hook "glDrawElements", but it doesn't work.

### ISSUE THREAD

**Issue by terieqin** [kubo/plthook#25]
I can hook "eglSwapBuffers", "malloc" function, it works well. 

But any opengl es function in android platform can not be hooked. I don't know why.

**Comment by kubo** [comment]
@terieqin 
Could you post more information? "can not be hooked" is too simple. Could you post what you expected and what you got?

Could you post workable sample code with project files to reproduce the issue?
I don't know how to use opengl es functions and how to make Android applications except small programs using `ndk-build`.

**Comment by kubo** [comment]
No update. Closed.
