### ISSUE TITLE
[Android] Hook dlopen 

### ISSUE THREAD

**Issue by Ali-Khazaee** [kubo/plthook#26]
As root user is it possible to hook dlopen to get reading & writing access on /proc/$pid/mem ?

**Comment by kubo** [comment]
I don't have enougth knowledge whether it is possible on Android.
However I guess that it may be possible.

1. Create a function which hooks dlopen (by plthook) against the target executable and all loaded shared libraries.
2. Create a shared library which calls the above function when it is loaded. See [\_\_attribute\_\_ ((\_\_constructor\_\_))](https://www.google.com/search?q=__attribute__+%28%28__constructor__%29%29)
3. Inject the shared library. See https://fadeevab.com/shared-library-injection-on-android-8/
