### ISSUE TITLE
Why mprotect not needed for osx?

### ISSUE THREAD

**Issue by krackers** [kubo/plthook#38]
HI,

Thank you for a wonderful tool. I was curious why mprotect(PROT_WRITE) was not needed before modifying the PLT on osx? I thought that __TEXT and __LINKEDIT segments did not have write permission?

**Comment by krackers** [comment]
Ah the PLT is part of __DATA__ segment which has rw permission.

**Comment by kubo** [comment]
> if we dyld does lazy binding, isn't it possible that our modification to PLT will get overwritten when we call original function (which if not previously bound will invoke dyld first?)

It isn't as far as I googled.
See "Lazy vs. non-lazy symbol binding" in https://adrummond.net/posts/macho.
