### ISSUE TITLE
strcmp() in plthook_replace() causes segfault on Windows

### ISSUE THREAD

**Issue by UberLambda** [kubo/plthook#7]
The strcmp() at [`plthook_win32.c:241`](https://github.com/kubo/plthook/blob/676a3fc27ee2ae1afe2c3e2f58aac2bfe669c010/plthook_win32.c#L241) sometimes causes a segmentation fault. This is because `name`s of entries in `plthook->entries` are sometimes null (such as for some entries in "Shell32.dll" on my Windows 10 install).

A simple workaround is to replace [`plthook_win32.c:241`](https://github.com/kubo/plthook/blob/676a3fc27ee2ae1afe2c3e2f58aac2bfe669c010/plthook_win32.c#L187) from
```c
plthook->entries[idx].name = name;
```
to
```c
plthook->entries[idx].name = name ? name : "(null)";
```

**Comment by kubo** [comment]
Thanks for the pointing!
I'll check it later.

**Comment by kubo** [comment]
The functions whose names are null is exported functions from a DLL by [ordinal][]. I fixed it.
Thanks again for reporting it.

[ordinal]: https://msdn.microsoft.com/en-us/library/e7tsx612.aspx
